name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    env: 
      NODE_ENV: testing
    
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
  
      - name: Make backend envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: "testing" 
          envkey_AUTH_SERVICE_MONGO_URI: "mongodb://127.0.0.1:27017/urlshortenertest"
          envkey_URL_SERVICE_MONGO_URI: "mongodb://127.0.0.1:27017/urlshortenertest"
          some_other_variable: foobar
          directory: "./apps"
          file_name: .env.testing
          fail_on_empty: false

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --target=build --parallel=3
